name: GitHub Actions Pusblish as .zip
on: [push]
jobs:
  To-Zip:
    runs-on: ubuntu-latest
    steps:
        - name: Commit and push
          uses: EndBug/add-and-commit@v7
          with:
            add: '["folder.zip"]'
            message: 'My commit message'
            push: true

